configuratie = struct('procentYMin',       30,'pixeliXPotrivire', 100,...
                      'yInceputDecupare', 220,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 100,'xLungimeDecupare', 620);