configuratie = struct('procentYMin',       45,'pixeliXPotrivire', 45,...
                      'yInceputDecupare', 100,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 160,'xLungimeDecupare', 620);                  