% Configuratie pentru IPM
configuratie = struct('procentYMin',      65,'pixeliXPotrivire', 120,...
                      'yInceputDecupare', 100,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 160,'xLungimeDecupare', 620);                  