configuratie = struct('procentYMin',       20,'pixeliXPotrivire', 100,...
                      'yInceputDecupare', 250,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 100,'xLungimeDecupare', 620);