configuratie = struct('procentYMin',       50,'pixeliXPotrivire', 65,...
                      'yInceputDecupare', 10,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 100,'xLungimeDecupare', 204);