configuratie = struct('procentYMin',       80,'pixeliXPotrivire', 200,...
                      'yInceputDecupare', 70,'xInceputDecupare', 1,...
                      'yLungimeDecupare', 150,'xLungimeDecupare', 620);
                  