configuratie_detectie = struct('procentYMin',       48,'pixeliXPotrivire', 85,...
                      'yInceputDecupare', 200,'xInceputDecupare', 200,...
                      'yLungimeDecupare', 225,'xLungimeDecupare', 482);