configuratie = struct('procentYMin',       10,'pixeliXPotrivire', 65,...
                      'yInceputDecupare', 190,'xInceputDecupare', 60,...
                      'yLungimeDecupare', 100,'xLungimeDecupare', 500);

% Configuratie detectie masina
% configuratie = struct('procentYMin',       50,'pixeliXPotrivire', 45,...
%                       'yInceputDecupare', 40,'xInceputDecupare', 60,...
%                       'yLungimeDecupare', 300,'xLungimeDecupare', 500);