configuratie = struct('procentYMin',       50,'pixeliXPotrivire', 85,...
                      'yInceputDecupare', 100,'xInceputDecupare', 200,...
                      'yLungimeDecupare', 325,'xLungimeDecupare', 482);