configuratie = struct('procentYMin',       80,'pixeliXPotrivire', 100,...
                      'yInceputDecupare', 100,'xInceputDecupare', 100,...
                      'yLungimeDecupare', 180,'xLungimeDecupare', 420);