% Configuratie pentru IPM
configuratie = struct('procentYMin',      45,'pixeliXPotrivire', 65,...
                      'yInceputDecupare', 500,'xInceputDecupare', 950,...
                      'yLungimeDecupare', 150,'xLungimeDecupare', 340);
parametri.threshold = 2.5;