% Configuratie pentru IPM
configuratie = struct('procentYMin',      55,'pixeliXPotrivire', 95,...
                      'yInceputDecupare', 115,'xInceputDecupare', 95,...
                      'yLungimeDecupare', 170,'xLungimeDecupare', 540);
parametri.threshold = 2.5;