configuratie = struct('procentYMin',       75,'pixeliXPotrivire', 100,...
                      'yInceputDecupare', 150,'xInceputDecupare', 5,...
                      'yLungimeDecupare', 200,'xLungimeDecupare', 600);           
parametri.threshold = 3.5;  

% marcaje ceata
% configuratie = struct('procentYMin',       35,'pixeliXPotrivire', 100,...
%                       'yInceputDecupare', 200,'xInceputDecupare', 1,...
%                       'yLungimeDecupare', 150,'xLungimeDecupare', 620);   

% marcaje ploaie
% configuratie = struct('procentYMin',       35,'pixeliXPotrivire', 80,...
%                       'yInceputDecupare', 150,'xInceputDecupare', 30,...
%                       'yLungimeDecupare', 200,'xLungimeDecupare', 590);  