configuratie = struct('procentYMin',       80,'pixeliXPotrivire', 110,...
                      'yInceputDecupare', 100,'xInceputDecupare', 50,...
                      'yLungimeDecupare', 150,'xLungimeDecupare', 420);