configuratie = struct('procentYMin',       20,'pixeliXPotrivire', 75,...
                      'yInceputDecupare', 190,'xInceputDecupare', 60,...
                      'yLungimeDecupare', 100,'xLungimeDecupare', 500);